### PR TITLE
[DO NOT MERGE] Don't merge this PR, it's only a test for Telegram notification

### PR DESCRIPTION
**Pull request by masch**
Add an empty file to test TH GH action integration, this PR must be closed without merged it.

### CODE REVIEW

**Comment by santisiri** [comment]
No prob. Keep me posted.

**Comment by masch** [comment]
There is an issue on the chat_id. I'll check the documentation in order to get the correct value

**Comment by masch** [comment]
I'll reopen the PR in order to test the bot.

**Comment by santisiri** [comment]
Is this ready to be closed?

**Comment by masch** [comment]
Yes, as we already discussed it, we can close it, although it doesn't work the Telegram notification GitHub action on PR coming from forks. The reason for this is that repository secrets from GH cannot be shared between cross repository domains.
Since we are going to be work as collaborators of the repository, the plugin will be run ok.

**Pull request closed without merging**
